# from ... import... # link to image folders and img detection

# -*- coding: utf-8 -*-
"""Copy of Final Prj: 2D Mapping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yCk7FwP9_GDWUlmYD6ezXLKBdJGvxhwg

From Medium: https://medium.com/tech-that-works/how-does-panorama-work-image-stitching-bf1a9f0e4fa5

Github link: https://github.com/samrudh/Panorama-Effect-Image-Stitching/tree/master/code
"""

# helper functions

import cv2
import numpy as np
import random
from tqdm import tqdm
import matplotlib.pyplot as plt
from pathlib import Path

### DLT
def create_matrix_M(real_points , image_points, total_points):
    M = []  #np.empty([2*total_points, 12])
    for index in range(total_points):

        X,Y = real_points[index]
        x, y= image_points[index]

        # print("XYZ are :", X, Y, Z)
        # print("xyz are :", x, y, z)

        M.append([X,Y, 1, 0, 0,0,  -(x*X), -(x*Y), -x])
        M.append([ 0, 0, 0, X, Y, 1,  -(y * X), -(y * Y), -y])


    M = np.asarray(M)
    return M

# Homography
def dlt_calibrate(real_world_points, image_points, total_points):
    a = create_matrix_M(real_world_points, image_points, total_points)
    U, S, V = np.linalg.svd(a)

    P_vec = V[-1,:]
    ## Normalize
    P_vec = P_vec / V[-1,-1]

    # print("p vec after norm ", P_vec)
    P = np.reshape(P_vec, [3,3])
    # print("P is ", P)
    return P

def calculate_image_point(p_matrix, world_point, image_path, write = False, show= False, title="image"):
    x = np.dot(p_matrix, world_point.T)

    u, v, w = list(x)
    xx =  int(u/w)
    yy = int(v/w)

    return  xx, yy

### RANSAC
def ransac_calibrate(real_points , image_points, total_points, image_path, iterations):
    index_list = list(range(total_points))
    iterations = min(total_points - 1, iterations)
    errors = list(np.zeros(iterations))
    combinations = []
    p_estimations=[]

    for i in range(iterations):
        selected = random.sample(index_list,4)
        combinations.append(selected)

#        print("selected",selected)
        real_selected =[]
        image_selected =[]

        for x in selected:
            real_selected.append(real_points[x])
            image_selected.append(image_points[x])


        p_estimated = dlt_calibrate(real_selected, image_selected, 4)


        not_selected = list(set(index_list) - set(selected))
        error = 0
        for num in tqdm(not_selected):

            # get points from the estimation
            test_point = list(real_points[num])
            test_point = [int(x) for x in test_point]
            test_point = test_point + [1]

            try:
                xest, yest = calculate_image_point(p_estimated, np.array(test_point), image_path)
            except ValueError:

                continue

            error = error + np.square(abs(np.array(image_points[num])-np.asarray([xest,yest])))
#           print("estimated  :",np.array([xest, yest])  )
#           print("actual :",image_points[0])
#           print("error :",error)
        errors.append(np.mean(error))
        p_estimations.append(p_estimated)

    p_final = p_estimations[errors.index(min(errors))]
    return p_final ,errors, p_estimations

# from pathlib import Path
# def get_image_dict(directory_path):
#   image_dict = {}
#   # directory_path = Path("/content")
#   for file_path in directory_path.iterdir():
#       if file_path.is_file():
#           file_name = str(file_path)[9:]
#           # print(file_name)
#           cleaned = file_name.split(".png")[0]
#           separated = cleaned.split("_")
#           print(separated)
#           # print(separated)
#           x, y, yaw = float(separated[0]), float(separated[1]), float(separated[3])

#           if x not in image_dict:
#               image_dict[x] = []
#           image_dict[x].append([y, yaw])
#           #image_list.append((x, y, yaw))
#           #print(image_list)
#   return image_dict

# coords = get_image_dict(Path("/content"))
# print(coords)

# def snake_sort(coords_dict):
#   sorted_dict = {k: coords_dict[k] for k in sorted(coords_dict.keys())}
#   iter_count = 0
#   for key in sorted_dict: # Iterate by key to modify values in place
#       if iter_count % 2 == 1:
#         sorted_dict[key] = sorted(sorted_dict[key], key=lambda x: x[0], reverse=True)
#       else:
#         sorted_dict[key] = sorted(sorted_dict[key], key=lambda x: x[0])
#       iter_count += 1
#   return sorted_dict

# def createPanorama(input_img_list):
#     images = []
#     dims = []
#     get_image_dict(Path("/content"))
#     for index, path in enumerate(input_img_list):
#         print (path)
#         images.append(cv2.imread(path))
#         dims.append(images[index].shape)
#     return images, dims

# def consistentize(coord):
#   str_coord = str(coord)
#   check_negative = str_coord
#   if check_negative[0] == '-':
#     check_negative = check_negative[1:]
#   if len(check_negative) == 3:
#     str_coord += '0'
#   elif len(check_negative) != 4:
#     print(f"coord != 4: {str_coord}")
#   return str_coord

# def createPanorama(images_path):
#   coords_dict = get_image_dict(Path(images_path))
#   print(f"coords: {coords_dict}")
#   snake_sorted = snake_sort(coords_dict)
#   print(f"snake: {snake_sorted}")
#   image_list = []
#   dim_list = []
#   for key, value in snake_sorted.items():
#     for val in value:
#       plt.scatter(key, val[0])
#       path = "/content/" + consistentize(key) + "_" + consistentize(val[0]) + "__" + consistentize(val[1]) + ".png"
#       image = cv2.imread(path)
#       if image is None:
#           print(f"Warning: Could not read image at path: {path}. Skipping this image.")
#           continue
#       image_list.append(image)
#       dim_list.append(image_list[-1].shape)
#   return image_list, dim_list

# img, dim = createPanorama("/content")

# from pathlib import Path
def createPlots(images_path):
  # coords_dict = get_image_dict(Path(images_path))
  # print(f"coords: {coords_dict}")
  # snake_sorted = snake_sort(coords_dict)
  # print(f"snake: {snake_sorted}")
  image_coords = []
  images = []
  for file_path in images_path.iterdir():
      if file_path.is_file():
          file_name = str(file_path)[9:]
          # print(file_name)
          cleaned = file_name.split(".png")[0]
          separated = cleaned.split("_")
          #print(separated)
          # print(separated)
          x, y, yaw = float(separated[0]), float(separated[1]), float(separated[3])
          image_coords.append((x, y))
          plt.scatter(x, y)

createPlots(Path("/content"))

from pathlib import Path

def extract_coords(file_path):
  file_name = str(file_path)[9:]
  # print(file_name)
  cleaned = file_name.split(".png")[0]
  separated = cleaned.split("_")
  #print(separated)
  # print(separated)
  x, y, yaw = float(separated[0]), float(separated[1]), float(separated[3])
  return x, y, yaw

def get_image_pathway_raw(directory_path):

  minx = None
  maxx = None
  miny = None
  maxy = None

  main_x = [[], [], [], [], [], []]
  main_y = [[], [], [], [], [], []]
  xy = []
  # range: [-1.5, -1.25], [-1.25, -0.75],....
  # directory_path = Path("/content")
  for file_path in directory_path.iterdir():

      if file_path == directory_path[0]:
          print(file_path)
          continue
      if file_path.is_file():
          x, y, yaw = extract_coords(file_path)
          if minx is None:
              minx = x
          elif minx > x:
              minx = x
          if maxx is None:
              maxx = x
          elif maxx < x:
              maxx = x
          if miny is None:
              miny = y
          elif miny > y:
              miny = y
          if maxy is None:
              maxy = y
          elif maxy < y:
              maxy = y

  rangex = (maxx - minx)//0.5 + 1 # how many discretized value?
  print(f"rangex: {rangex}")
  temp = minx + 0.5
  groupx = {temp:[]}
  for i in range(1, rangex-1):
    temp = minx + (i+1)*0.5
    groupx[temp] = []

  rangey = (maxy - miny)//0.5 + 1
  print(f"rangey: {rangey}")
  temp = miny + 0.5
  groupy = {temp:[]}
  for i in range(1, rangey-1):
    temp = miny + (i+1)*0.5
    groupy[temp] = []

  print(f"groupy: {groupy}, len: {len(groupy)}")
  print(f"groupx: {groupx}, len: {len(groupx)}")

  for file_path in directory_path.iterdir():
      if file_path.is_file():
          x, y, yaw = extract_coords(file_path)
          added = 0
          for kx in groupx.keys():
            if kx <= x < kx + 0.5:
              groupx[kx].append((x, y, yaw))
              added += 1
          for ky in groupy.keys():
            if ky <= y < ky + 0.5:
              groupy[ky].append((x, y, yaw))
              added += 1
            if added == 2:
                xy.append((x, y, yaw))
            #image_list.append((x, y, yaw))
          #print(image_list)
  # print("before removal")
  # print(len(main_x))
  # print(len(main_y))
  # for e in main_x:
  #   print(e)
  #   # if len(e) < 5:
  #   #   print("x removing..")
  #   #   main_x.remove(e)
  # for e in main_y:
  #   print(e)
  #   # if len(e) < 5:
  #   #   print("y removing..")
  #   #   main_y.remove(e)
  # print("after removal")
  # print(len(main_x))
  # print(len(main_y))
  # hard code
  # sorted_main_xmax = sorted(main_x[5], key=lambda x:x[1], reverse=True)
  # sorted_main_ymin = sorted(main_y[5], key=lambda x:x[0], reverse=True)
  # sorted_main_xmin = sorted(main_x[0], key=lambda x:x[1])
  # sorted_main_ymax = sorted(main_y[0], key=lambda x:x[0])

  sorted_main_xmax = sorted(main_x[5], key=lambda x:x[1])
  sorted_main_ymax = sorted(main_y[5], key=lambda x:x[0], reverse=True)
  sorted_main_xmin = sorted(main_x[0], key=lambda x:x[1], reverse=True)
  sorted_main_ymin = sorted(main_y[0], key=lambda x:x[0])
  # print(len(sorted_main_xmin))
  # print(len(sorted_main_xmax))
  # print(len(sorted_main_ymax))
  # print(len(sorted_main_ymin))

  pathway_list = sorted_main_xmin + sorted_main_ymax + sorted_main_xmax + sorted_main_ymin

  # temp
  # pathway_list = sorted_main_ymin
  # pathway_list = []
  # pathway_list.append(sorted_main_ymax)
  # pathway_list.append(sorted_main_xmin)
  # pathway_list.append(sorted_main_ymin)
  # pathway_list.append(sorted_main_xmax)
  print(pathway_list)
  # print(len(pathway_list))
  # print(pathway_list)
  # pathway = set(pathway_list)
  return pathway_list

coords = get_image_pathway_raw(Path("/content"))
#print(coords)



def consistentize(coord):
  str_coord = str(coord)
  check_negative = str_coord
  if check_negative[0] == '-':
    check_negative = check_negative[1:]
  if len(check_negative) == 3:
    str_coord += '0'
  elif len(check_negative) != 4:
    print(f"coord != 4: {str_coord}")
  return str_coord

def createPanorama(images_path):
  # coords_dict = get_image_dict(Path(images_path))
  # print(f"coords: {coords_dict}")
  # snake_sorted = snake_sort(coords_dict)
  # print(f"snake: {snake_sorted}")
  paths = get_image_pathway_raw(Path(images_path))
  image_list = []
  dim_list = []
  # for key, value in snake_sorted.items():
  #   for val in value:
  #     plt.scatter(key, val[0])
  #     path = "/content/" + consistentize(key) + "_" + consistentize(val[0]) + "__" + consistentize(val[1]) + ".png"
  #     image = cv2.imread(path)
  #     if image is None:
  #         print(f"Warning: Could not read image at path: {path}. Skipping this image.")
  #         continue
  for path in paths:
    plt.scatter(path[0], path[1])
    pathway = "/content/" + consistentize(path[0]) + "_" + consistentize(path[1]) + "__" + consistentize(path[2]) + ".png"
    image = cv2.imread(pathway)
    if image is None:
        print(f"Warning: Could not read image at path: {pathway}. Skipping this image.")
    image_list.append(image)
    dim_list.append(image_list[-1].shape)
  return image_list, dim_list

img, dim = createPanorama("/content")



print("/content/-1.45_-0.90__-3.09.png" == "/content/-1.45_-0.9__-3.09.png")
print("-1.44" == str(-1.44))
print(str(-1.44)[1:])

def reSizeImages(images, dims):
    ht , _, _= min(dims,  key = lambda val: val[0])
    _, wt, _= min(dims,  key = lambda val: val[1])
    _, _, ch = min(dims,  key = lambda val: val[2])
    print("resizing to :", ht, wt)
    images= [cv2.resize(x, (ht, wt))  for x in images]
    blank  = np.zeros((wt,ht,ch), np.uint8)
    return images, blank

def compute_canvas(image1, warped_corners2):

    h1, w1 = image1.shape[:2]

    corners1 = np.float32(
        [[0,0],
        [w1,0],
        [w1,h1],
        [0,h1]]
    )

    all_corners = np.vstack((corners1, warped_corners2.reshape(-1,2)))

    xmin, ymin = np.int32(all_corners.min(axis=0))
    xmax, ymax = np.int32(all_corners.max(axis=0))

    width = xmax - xmin
    height = ymax - ymin

    T = np.array(
        [[1,0,-xmin],
        [0,1,-ymin],
        [0,0,1]], dtype=np.float32
    )

    return width, height, T

def getMatches(color_image1, color_image2, features, ransac_iterations = 150, dist_threshold = 0.7, image_cen = []):
    # Convert to grayscale for feature detection
    image1_gray = cv2.cvtColor(color_image1, cv2.COLOR_BGR2GRAY)
    image2_gray = cv2.cvtColor(color_image2, cv2.COLOR_BGR2GRAY)

    points1, des1 = features.detectAndCompute(image1_gray,  None)
    points2, des2 = features.detectAndCompute(image2_gray,  None)

    imp = []

    ## Define flann based matcher
    matcher = cv2.FlannBasedMatcher()
    matches = matcher.knnMatch(des1,des2,k=2)

    # important features
    goodmatches = []
    for i, (one, two) in enumerate(matches):
        if one.distance < dist_threshold*two.distance:
            imp.append((one.trainIdx, one.queryIdx))
            goodmatches.append([one])

    matched1 = np.float32([points1[i].pt for (__, i) in imp])
    matched2 = np.float32([points2[i].pt for (i,__) in imp])


    print("len of matched features :", matched1.shape[0])
    # FIX: Use cv2.drawMatchesKnn for goodmatches which is a list of lists
    matches_output = np.zeros((max(color_image1.shape[0], color_image2.shape[0]), color_image1.shape[1] + color_image2.shape[1], 3), dtype=np.uint8)
    drawn = cv2.drawMatchesKnn(color_image1, points1, color_image2, points2, goodmatches, matches_output, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    plt.imshow(drawn), plt.show()

    ## to prevent whole pic tilt:
    # Use Affine Partial 2D to reduce tilt
    H_affine, inliers = cv2.estimateAffinePartial2D(matched2, matched1)

    # Handle cases where affine transformation cannot be estimated (e.g., too few matches)
    if H_affine is None:
        print("Warning: Could not estimate Affine Partial 2D. Returning previous panorama.")
        # In a real application, you might want to handle this differently, e.g., raise an error
        # or return a specific error code. For now, using an identity matrix as a fallback.
        H = np.eye(3, dtype=np.float32) # Use identity matrix as a fallback
    else:
        # Convert 2x3 affine matrix to 3x3 homography matrix for perspective transformations
        H = np.vstack([H_affine, np.array([0, 0, 1.0])]) # Use H for consistency with subsequent code

    # Comment out Homography as it's not working well for tilt
    # H, s = cv2.findHomography(matched2, matched1 , cv2.RANSAC, 5.0)

    h1, w1 = color_image1.shape[:2]
    h2, w2 = color_image2.shape[:2]

    # Calculate corners of image2 and warp them
    corners = np.float32([[0,0],[w2,0],[w2,h2],[0,h2]]).reshape(-1,1,2)
    warped_corners = cv2.perspectiveTransform(corners, H)

    # Get the canvas dimensions and translation matrix T
    canvas_width, canvas_height, T_matrix = compute_canvas(color_image1, warped_corners)

    # --- Start of fix for image_cen handling ---
    new_image_cen = []
    if len(image_cen) > 0:
        cleaned_image_cen = []
        for item in image_cen:
            if isinstance(item, tuple) and len(item) == 2:
                cleaned_image_cen.append(item)
            elif isinstance(item, np.ndarray) and item.shape == (1, 1, 2):
                # If it's a 1x1x2 numpy array (like the problematic one), extract the tuple
                cleaned_image_cen.append(tuple(item[0][0]))
            else:
                # Log a warning if an unexpected type is encountered, but try to continue
                print(f"Warning: image_cen contained an unexpected item type/shape: {type(item)}, value: {item}. Skipping.")

        if len(cleaned_image_cen) > 0:
            # Convert list of cleaned tuples to numpy array for perspectiveTransform
            # Ensure consistent float32 type for transformation
            pts_to_transform = np.array(cleaned_image_cen, dtype=np.float32).reshape(-1, 1, 2)
            transformed_existing_pts = cv2.perspectiveTransform(pts_to_transform, T_matrix @ H)
            new_image_cen = [tuple(pt[0]) for pt in transformed_existing_pts] # Convert back to list of tuples

    # Warp image1 with only the translation matrix T_matrix
    # All matched points fit one transformation -- background looks weird
    warped_im1 = cv2.warpPerspective(color_image1, T_matrix, (canvas_width, canvas_height))

    # Warp image2 with H and T_matrix to get its position on the final canvas
    warped_im2 = cv2.warpPerspective(color_image2, T_matrix @ H, (canvas_width, canvas_height))

    # Getting Center of image1 (the newly added image)
    center_new_image_orig = np.array([[[w1/2, h1/2]]], dtype=np.float32)
    transformed_center_new_image = cv2.perspectiveTransform(center_new_image_orig, T_matrix)
    new_image_cen.append(tuple(transformed_center_new_image[0][0])) # Append as tuple

    # --- End of fix for image_cen handling ---

    # Combine the two warped images by taking the maximum pixel values (non-zero merge)
    out = np.maximum(warped_im1, warped_im2)
    # out = np.where(warped_im2 == 0, warped_im2, np.maximum(warped_im1, warped_im2))
    final_out = getNonZeroImage(out)

    return final_out, out , des1[0], new_image_cen # Return the updated image_cen

def getNonZeroImage(image):

    ## keep nonzero pixels
    out_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    pixels = cv2.findNonZero(out_gray)
    pixels = pixels.reshape([pixels.shape[0],2])

    extreme_min_x = min(pixels[:,0])
    extreme_max_x = max(pixels[:,0])
    extreme_min_y = min(pixels[:,1])
    extreme_max_y = max(pixels[:,1])

    ## clip with extremes
    print("ys :",extreme_min_y, extreme_max_y)
    print("xs :",extreme_min_x, extreme_max_x)

    image = image[extreme_min_y:extreme_max_y, extreme_min_x:extreme_max_x,:]
    return image

def showAndWrite(output, temp, img_cen, path="content/out.png"):
    import matplotlib.pyplot as plt
    import cv2

    output = getNonZeroImage(output)

    plt.figure(figsize=(12, 4))

    plt.subplot(1, 2, 1)
    plt.imshow(cv2.cvtColor(output, cv2.COLOR_BGR2RGB))
    # plt.title("Panorama")
    plt.axis("on")

    for c in range(len(img_cen)):
        print(f"image_cen:{img_cen[c]}")
        label = f"point{c}"
        plt.plot(img_cen[c][0], img_cen[c][1], 'ro', markersize=5, label=label)
        plt.legend()
    # plt.subplot(1, 2, 2)
    # plt.imshow(cv2.cvtColor(temp, cv2.COLOR_BGR2RGB))
    # plt.title("Temp")
    # plt.axis("off")

    plt.show()

    #cv2.imwrite(path, output)
    #cv2.imwrite("temp.png", temp)

import cv2
print(cv2.__version__)
print(hasattr(cv2, "SIFT_create"))

if __name__ =="__main__":
  # image_list = constants.image_list
  # image_list = ["/content/img1_1.png", "/content/img1_2.png"]
  #  image_list = ["/content/-1.40_0.20_3.14.png", "/content/-1.41_-0.35_3.12.png", "/content/-1.42_-0.91_3.10.png"]
  #  image_list = ["0.10_-1.46_-1.57.png", "0.20_1.45_1.69.png", "-0.40_-1.44_-1.51.png", "0.75_1.45_1.71.png"]
  #  image_list = ["content/1.37_1.46_1.79.png", "content/-1.42_1.38_-3.10.png", "content/1.45_-1.28_0.02.png"]
  #  image_list = ["/content/test2_1.jpg", "/content/test2_2.jpg"]


    images , dims = createPanorama("/content")
  #  images = images[8::]
  #  (-1.44, 0.2, -3.08), (-1.44, -0.35, -3.06)
    # image_list = ["/content/-1.44_0.75__-3.05.png", "/content/-1.44_0.20__-3.08.png", "/content/-1.44_-0.35__-3.06.png"]
    # #, ]
    # (-1.44, 1.31, -3.0), (-1.45, 1.45, -3.11)
    # image_list = ["/content/-1.44_1.31__-3.00.png", "/content/-1.45_1.45__-3.11.png"] #, "/content/-1.44_-0.35__-3.06.png"]

    # (-1.45, 1.45, -3.11), (-1.44, 1.31, -3.0), (-1.44, 0.75, -3.05), (-1.44, 0.2, -3.08)
    # image_list = ["/content/-1.45_1.45__-3.11.png", "/content/-1.44_1.31__-3.00.png", "/content/-1.44_0.75__-3.05.png", "/content/-1.44_0.20__-3.08.png"] #, "/content/-1.44_-0.35__-3.06.png"]

    # images = [cv2.imread(img) for img in image_list]
    # dims = [img.shape for img in images]
    # images, blank = reSizeImages(images, dims)

    ## Define feature type
    feature_type = cv2.SIFT_create()
    # feature_type = cv2.xfeatures2d.SIFT_create()

    # Initialize image_cen with the center of the first image
    initial_img_h, initial_img_w = images[0].shape[:2]
    image_cen = [ (float(initial_img_w)/2, float(initial_img_h)/2) ] # Store as tuple directly, converted to float

    out = images[0]
    # temp = out # Initialize temp before the loop
    i = 1
    # dist_thresh = [0.9, 0.7, 0.5, 0.5, 0.5, 0.5]
    # dist_thresh = [0.5, 0.4, 0.3, 0.3, 0.3, 0.3]
    for index in range(len(images) - 1):
        print('index :', index)
        im2 = images[index+1] ## was Added Undistort


        plt.imshow(cv2.cvtColor(out, cv2.COLOR_BGR2RGB))
        plt.title("imshow out")
        plt.show()
        # gray2 = cv2.cvtColor(im2, cv2.COLOR_BGR2GRAY)
        # gray1 = cv2.cvtColor(out, cv2.COLOR_BGR2GRAY) # Added Undistort

        try:
          out ,temp, z, image_cen = getMatches(im2, out, feature_type, ransac_iterations = 1000, dist_threshold=0.5, image_cen=image_cen)
        except:
          path = "wall" + str(i) + ".png"
          print(f"path: {path}")
          cv2.imwrite(path, out)
          i += 1
          out = im2
          image_cen = [image_cen[-1]]
          print("error")
          continue
        # print(f"coord1:{coord1}, coord2:{coord2}")
        print(image_cen)
        # if(index == 0):
        #     img_cen.append(coord1)
        # img_cen.append(coord2)
        # print(img_cen)
        outshape = out.shape
        showAndWrite(out, temp, image_cen, path ="result"+str(index) + ".png")

    out = getNonZeroImage(out)
    showAndWrite(out, temp, image_cen, path ="taj_f_"+str(index) + ".png")

images, dims = createPanorama("/content")

feature_type = cv2.SIFT_create()

initial_img_h, initial_img_w = images[0].shape[:2]
image_cen = [(float(initial_img_w)/2, float(initial_img_h)/2)]

out = images[0]

dist_thresh = [0.5, 0.4, 0.3, 0.3, 0.3, 0.3]

START = 0  # where your main loop begins

# ── Phase 1: silently build panorama up to index START ──────────────────
for index in range(0, START):
    im2 = images[index + 1]
    threshold = dist_thresh[index] if index < len(dist_thresh) else dist_thresh[-1]
    try:
        out, temp, z, image_cen = getMatches(
            im2, out, feature_type,
            ransac_iterations=1000,
            dist_threshold=threshold,
            image_cen=image_cen
        )
        print(f"[warmup] stitched index {index} → {index+1}")
    except Exception as e:
        out = images[index + 1]
        print(f"[warmup] error at index {index}: {e}, skipping")
        continue

# ── Phase 2: main loop from START onwards ───────────────────────────────
for index in range(START, len(images) - 1):
    print('index :', index)
    im2 = images[index + 1]

    plt.imshow(cv2.cvtColor(out, cv2.COLOR_BGR2RGB))
    plt.show()

    threshold = dist_thresh[index] if index < len(dist_thresh) else dist_thresh[-1]

    try:
        out, temp, z, image_cen = getMatches(
            im2, out, feature_type,
            ransac_iterations=1000,
            dist_threshold=threshold,
            image_cen=image_cen
        )
    except Exception as e:
        out = im2
        print(f"error: {e}")
        continue

    print(image_cen)
    showAndWrite(out, temp, image_cen, path="result" + str(index) + ".png")

out = getNonZeroImage(out)
showAndWrite(out, temp, image_cen, path="taj_f_" + str(index) + ".png")

# Phase 1 warmup
for index in range(0, START):
    im2 = images[index + 1]
    threshold = dist_thresh[index] if index < len(dist_thresh) else dist_thresh[-1]
    try:
        out, temp, z, image_cen = getMatches(
            im2, out, feature_type,
            ransac_iterations=1000,
            dist_threshold=threshold,
            image_cen=image_cen
        )
        print(f"[warmup] stitched {index} → {index+1}")
    except Exception as e:
        print(f"[warmup] SKIPPING index {index}: {e}")
        # ← do NOT replace out, just skip this image
        continue

# Phase 2 main loop
for index in range(START, len(images) - 1):
    im2 = images[index + 1]
    threshold = dist_thresh[index] if index < len(dist_thresh) else dist_thresh[-1]
    try:
        out, temp, z, image_cen = getMatches(
            im2, out, feature_type,
            ransac_iterations=1000,
            dist_threshold=threshold,
            image_cen=image_cen
        )
    except Exception as e:
        print(f"SKIPPING index {index}: {e}")
        # ← do NOT replace out, preserve the last good panorama
        continue

    print(image_cen)
    showAndWrite(out, temp, image_cen, path="result" + str(index) + ".png")





from google.colab import drive
drive.mount('/content/drive')

"""My Test"""

import matplotlib.pyplot as plt
import numpy as np

images , dims = createPanorama("/content")

def plot_image_list(images, cols=4):
    n_images = len(images)
    rows = (n_images // cols) + (1 if n_images % cols > 0 else 0)

    # Create the figure and axes
    fig, axes = plt.subplots(rows, cols, figsize=(15, 4 * rows))

    # Flatten axes for easy iteration if it's a 2D array
    axes = axes.flatten() if n_images > 1 else [axes]

    for i in range(n_images):
        axes[i].imshow(images[i])
        axes[i].axis('off')  # Hide pixel coordinates for a cleaner look

    # Remove any extra empty subplots
    for j in range(i + 1, len(axes)):
        axes[j].axis('off')

    plt.tight_layout() # Minimize space between images
    plt.show()

plot_image_list(images)